### PR TITLE
fix(#93): removed `seq` atom + added flag for runtime semver

### LINKED ISSUE #93: Update EO version and remove `seq` atom
Since [this](https://github.com/objectionary/eo/issues/3078) is resolved - we should update version of EO and remove `seq` atom

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #93

---

## PR-Codex overview
The focus of this PR is to update test functions to include a `done` callback for asynchronous testing and handle exceptions in the test command execution.

### Detailed summary
- Added `done` callback to test functions for asynchronous testing
- Handled exceptions in test command execution
- Added `runtimeVersion` option for specifying eo2js-runtime version
- Refactored `pckg` function to accept an `options` object
- Updated package.json generation based on program options

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +20 points for this. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+40](https://objectionary.github.io/eo/zerocracy.html).

**Pull request merged**
